main:
  - title: "Home"
    url: /
  - title: "Case Studies"
    url: /case-studies/
  - title: "AI Concepts"
    url: /concepts/
  - title: "Projects"
    url: /projects/
  - title: "Resume"
    url: /resume/
  - title: "About"
    url: /about/
  - title: "Contact"
    url: /contact/
