title: "Anagha Shevade"
description: "AI Enablement + Analytics â€” case studies, concepts, and projects"
url: "https://anaghashevade.github.io"
baseurl: ""
markdown: kramdown
highlighter: rouge
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

collections:
  case_studies:
    output: true
    permalink: /case-studies/:name/
  concepts:
    output: true
    permalink: /concepts/:name/
  projects:
    output: true
    permalink: /projects/:name/

include:
  - _pages
